name: CI
 
on:
  push:
    branches:
      - dev
      - chore/setup-infra
  pull_request:
    branches:
      - dev
 
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: |
            apps/gateway/pnpm-lock.yaml
            apps/auth-service/pnpm-lock.yaml
            apps/transjatim-service/pnpm-lock.yaml

      - name: Install gateway dependencies
        working-directory: apps/gateway
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install auth-service dependencies
        working-directory: apps/auth-service
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install transjatim-service dependencies
        working-directory: apps/transjatim-service
        run: pnpm install --frozen-lockfile --ignore-scripts

     
      - name: Test gateway
        working-directory: apps/gateway
        run: pnpm test --passWithNoTests

      - name: Test auth-service
        working-directory: apps/auth-service
        run: pnpm test --passWithNoTests

      - name: Test transjatim-service
        working-directory: apps/transjatim-service
        run: pnpm test --passWithNoTests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=capstone-majadigi-4
            -Dsonar.projectKey=Capstone-Majadigi-4_majadigi-superapp
            -Dsonar.sources=apps
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

  
